<a href="https://colab.research.google.com/github/tu26010-7431-hue/Tu26010/blob/main/Ch06_Ex04_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [2]:
data4 = {
    'id':['0','1','2','3','4','6','8','11','12','13'],
    'city':['Tokyo','Osaka','Kyoto','Hokkaido','Tokyo','Tokyo','Osaka','Kyoto','Hokkaido','Tokyo'],
    'birth_year':[1990,1989,1992,1997,1982,1991,1988,1990,1995,1981],
    'name':['Hiroshi','Akiko','Yuki','Satoru','Steeve','Mituru','Aoi','Tarou','Suguru','Mitsuo']
}
df4 = DataFrame(data4)
df4

   id      city  birth_year     name
0   0     Tokyo        1990  Hiroshi
1   1     Osaka        1989    Akiko
2   2     Kyoto        1992     Yuki
3   3  Hokkaido        1997   Satoru
4   4     Tokyo        1982   Steeve
5   6     Tokyo        1991   Mituru
6   8     Osaka        1988      Aoi
7  11     Kyoto        1990    Tarou
8  12  Hokkaido        1995   Suguru
9  13     Tokyo        1981   Mitsuo

In [3]:
data5 ={
    'id':['0','1','3','6','8'],
    'math':[20,30,50,70,90],
    'english':[30,50,50,70,90],
    'sex':['M','F','F','M','M'],
    'index_num':[0,1,2,3,4]
}
df5 = DataFrame(data5)
df5

  id  math  english sex  index_num
0  0    20       30   M          0
1  1    30       50   F          1
2  3    50       50   F          2
3  6    70       70   M          3
4  8    90       90   M          4

In [4]:
# 6-4
pd.merge(df4,df5,on= 'id')

  id      city  birth_year     name  math  english sex  index_num
0  0     Tokyo        1990  Hiroshi    20       30   M          0
1  1     Osaka        1989    Akiko    30       50   F          1
2  3  Hokkaido        1997   Satoru    50       50   F          2
3  6     Tokyo        1991   Mituru    70       70   M          3
4  8     Osaka        1988      Aoi    90       90   M          4

In [5]:
# 6-5
pd.merge(df4,df5,how='outer')

   id      city  birth_year     name  math  english  sex  index_num
0   0     Tokyo        1990  Hiroshi  20.0     30.0    M        0.0
1   1     Osaka        1989    Akiko  30.0     50.0    F        1.0
2  11     Kyoto        1990    Tarou   NaN      NaN  NaN        NaN
3  12  Hokkaido        1995   Suguru   NaN      NaN  NaN        NaN
4  13     Tokyo        1981   Mitsuo   NaN      NaN  NaN        NaN
5   2     Kyoto        1992     Yuki   NaN      NaN  NaN        NaN
6   3  Hokkaido        1997   Satoru  50.0     50.0    F        2.0
7   4     Tokyo        1982   Steeve   NaN      NaN  NaN        NaN
8   6     Tokyo        1991   Mituru  70.0     70.0    M        3.0
9   8     Osaka        1988      Aoi  90.0     90.0    M        4.0

In [6]:
data6 = {
    'id':['70','80','90','120','150'],
    'city':['Chiba','Kanagawa','Tokyo','Fukuoka','Okinawa'],
    'birth_year':[1980,1999,1995,1994,1994],
    'name':['Suguru','Kouichi','Satochi','Yukie','Akari']
}
df6 = DataFrame(data6)
df6

    id      city  birth_year     name
0   70     Chiba        1980   Suguru
1   80  Kanagawa        1999  Kouichi
2   90     Tokyo        1995  Satochi
3  120   Fukuoka        1994    Yukie
4  150   Okinawa        1994    Akari

In [7]:
# 6-6
concat_data = pd.concat([df4,df6])
concat_data

    id      city  birth_year     name
0    0     Tokyo        1990  Hiroshi
1    1     Osaka        1989    Akiko
2    2     Kyoto        1992     Yuki
3    3  Hokkaido        1997   Satoru
4    4     Tokyo        1982   Steeve
5    6     Tokyo        1991   Mituru
6    8     Osaka        1988      Aoi
7   11     Kyoto        1990    Tarou
8   12  Hokkaido        1995   Suguru
9   13     Tokyo        1981   Mitsuo
0   70     Chiba        1980   Suguru
1   80  Kanagawa        1999  Kouichi
2   90     Tokyo        1995  Satochi
3  120   Fukuoka        1994    Yukie
4  150   Okinawa        1994    Akari