<a href="https://colab.research.google.com/github/tu26010-7431-hue/Tu26010/blob/main/Ch06_Ex13-15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [2]:
from numpy import nan as NA

df2 = pd.DataFrame(np.random.rand(15, 6))
df2.iloc[2,0] = NA
df2.iloc[5:9,2] = NA
df2.iloc[7:10,3] = NA
df2.iloc[10,5] = NA

df2

           0         1         2         3         4         5
0   0.907521  0.119044  0.262135  0.112577  0.669182  0.235181
1   0.004066  0.451155  0.803137  0.402114  0.710967  0.046331
2        NaN  0.509124  0.723668  0.957654  0.485502  0.119131
3   0.622042  0.385190  0.043078  0.684812  0.887321  0.671762
4   0.399734  0.868696  0.621975  0.415114  0.381245  0.651249
5   0.974242  0.045088       NaN  0.695179  0.809284  0.147087
6   0.088601  0.317884       NaN  0.834784  0.127950  0.662381
7   0.297389  0.560211       NaN       NaN  0.966403  0.943125
8   0.883488  0.900284       NaN       NaN  0.781425  0.090323
9   0.156376  0.439824  0.539998       NaN  0.049153  0.205290
10  0.108054  0.120168  0.654095  0.576180  0.166596       NaN
11  0.172721  0.988172  0.196923  0.037934  0.423280  0.440430
12  0.895152  0.265488  0.408528  0.244381  0.537432  0.322408
13  0.791981  0.589537  0.530742  0.096119  0.770435  0.387652
14  0.965471  0.814825  0.263047  0.362371  0.346577  0.300804

In [3]:
# 6-13
df2.dropna()

           0         1         2         3         4         5
0   0.907521  0.119044  0.262135  0.112577  0.669182  0.235181
1   0.004066  0.451155  0.803137  0.402114  0.710967  0.046331
3   0.622042  0.385190  0.043078  0.684812  0.887321  0.671762
4   0.399734  0.868696  0.621975  0.415114  0.381245  0.651249
11  0.172721  0.988172  0.196923  0.037934  0.423280  0.440430
12  0.895152  0.265488  0.408528  0.244381  0.537432  0.322408
13  0.791981  0.589537  0.530742  0.096119  0.770435  0.387652
14  0.965471  0.814825  0.263047  0.362371  0.346577  0.300804

In [4]:
# 6-14
df2.fillna(0)

           0         1         2         3         4         5
0   0.907521  0.119044  0.262135  0.112577  0.669182  0.235181
1   0.004066  0.451155  0.803137  0.402114  0.710967  0.046331
2   0.000000  0.509124  0.723668  0.957654  0.485502  0.119131
3   0.622042  0.385190  0.043078  0.684812  0.887321  0.671762
4   0.399734  0.868696  0.621975  0.415114  0.381245  0.651249
5   0.974242  0.045088  0.000000  0.695179  0.809284  0.147087
6   0.088601  0.317884  0.000000  0.834784  0.127950  0.662381
7   0.297389  0.560211  0.000000  0.000000  0.966403  0.943125
8   0.883488  0.900284  0.000000  0.000000  0.781425  0.090323
9   0.156376  0.439824  0.539998  0.000000  0.049153  0.205290
10  0.108054  0.120168  0.654095  0.576180  0.166596  0.000000
11  0.172721  0.988172  0.196923  0.037934  0.423280  0.440430
12  0.895152  0.265488  0.408528  0.244381  0.537432  0.322408
13  0.791981  0.589537  0.530742  0.096119  0.770435  0.387652
14  0.965471  0.814825  0.263047  0.362371  0.346577  0.300804

In [5]:
# 6-15
df2.fillna(df2.mean())

           0         1         2         3         4         5
0   0.907521  0.119044  0.262135  0.112577  0.669182  0.235181
1   0.004066  0.451155  0.803137  0.402114  0.710967  0.046331
2   0.519060  0.509124  0.723668  0.957654  0.485502  0.119131
3   0.622042  0.385190  0.043078  0.684812  0.887321  0.671762
4   0.399734  0.868696  0.621975  0.415114  0.381245  0.651249
5   0.974242  0.045088  0.458848  0.695179  0.809284  0.147087
6   0.088601  0.317884  0.458848  0.834784  0.127950  0.662381
7   0.297389  0.560211  0.458848  0.451602  0.966403  0.943125
8   0.883488  0.900284  0.458848  0.451602  0.781425  0.090323
9   0.156376  0.439824  0.539998  0.451602  0.049153  0.205290
10  0.108054  0.120168  0.654095  0.576180  0.166596  0.373083
11  0.172721  0.988172  0.196923  0.037934  0.423280  0.440430
12  0.895152  0.265488  0.408528  0.244381  0.537432  0.322408
13  0.791981  0.589537  0.530742  0.096119  0.770435  0.387652
14  0.965471  0.814825  0.263047  0.362371  0.346577  0.300804