<a href="https://colab.research.google.com/github/tu26010-7431-hue/Tu26010/blob/main/Ch06_Cm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

%precision 3

'%.3f'

In [2]:
import requests,zipfile
from io import StringIO
import io

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00356/student.zip"
r = requests.get(url, stream=True)
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall()

In [3]:
student_data_math = pd.read_csv("student-mat.csv", sep=";")
student_data_math.groupby(['age','sex'])['G1'].mean().unstack()

sex          F          M
age
15   10.052632  12.250000
16   10.203704  11.740000
17   11.103448  10.600000
18   10.883721  10.538462
19   10.642857   9.700000
20   15.000000  13.000000
21         NaN  10.000000
22         NaN   6.000000

In [5]:
student_data_math.groupby(['age','sex'])['G1'].mean().unstack().dropna()

sex          F          M
age
15   10.052632  12.250000
16   10.203704  11.740000
17   11.103448  10.600000
18   10.883721  10.538462
19   10.642857   9.700000
20   15.000000  13.000000